package MySQL::Binlog::Constants;
# WARNING: Autogenerated file, do not edit!
use 5.008; use strict; use warnings;
use vars '@Names';
@Names = qw(
NEW_LOAD_EVENT SLAVE_EVENT WRITE_ROWS_EVENT_V1 ROTATE_EVENT ROWS_QUERY_LOG_EVENT DELETE_ROWS_EVENT_V1 INCIDENT_EVENT PRE_GA_DELETE_ROWS_EVENT TABLE_MAP_EVENT INTVAR_EVENT PRE_GA_UPDATE_ROWS_EVENT PREVIOUS_GTIDS_LOG_EVENT FORMAT_DESCRIPTION_EVENT EXEC_LOAD_EVENT ENUM_END_EVENT EXECUTE_LOAD_QUERY_EVENT XID_EVENT STOP_EVENT DELETE_FILE_EVENT LOAD_EVENT HEARTBEAT_LOG_EVENT BEGIN_LOAD_QUERY_EVENT PRE_GA_WRITE_ROWS_EVENT QUERY_EVENT USER_VAR_EVENT GTID_LOG_EVENT IGNORABLE_LOG_EVENT UPDATE_ROWS_EVENT_V1 CREATE_FILE_EVENT DELETE_ROWS_EVENT USER_DEFINED RAND_EVENT START_EVENT_V3 WRITE_ROWS_EVENT ANONYMOUS_GTID_LOG_EVENT UPDATE_ROWS_EVENT UNKNOWN_EVENT APPEND_BLOCK_EVENT STRING_TYPE REAL_TYPE INT_TYPE ROW_TYPE DECIMAL_TYPE VALUE_TYPE_COUNT STMT_END_F NO_FOREIGN_KEY_CHECKS_F RELAXED_UNIQUE_CHECKS_F COMPLETE_ROWS_F INVALID_INT_EVENT LAST_INSERT_ID_EVENT INSERT_ID_EVENT ERR_OK ERR_EOF ERR_FAIL ERR_CHECKSUM_ENABLED ERR_CHECKSUM_QUERY_FAIL ERR_CONNECT ERR_BINLOG_VERSION ERR_PACKET_LENGTH ERR_MYSQL_QUERY_FAIL ERROR_CODE_COUNT
);
package
  MySQL::Binlog;
sub NEW_LOAD_EVENT;
sub SLAVE_EVENT;
sub WRITE_ROWS_EVENT_V1;
sub ROTATE_EVENT;
sub ROWS_QUERY_LOG_EVENT;
sub DELETE_ROWS_EVENT_V1;
sub INCIDENT_EVENT;
sub PRE_GA_DELETE_ROWS_EVENT;
sub TABLE_MAP_EVENT;
sub INTVAR_EVENT;
sub PRE_GA_UPDATE_ROWS_EVENT;
sub PREVIOUS_GTIDS_LOG_EVENT;
sub FORMAT_DESCRIPTION_EVENT;
sub EXEC_LOAD_EVENT;
sub ENUM_END_EVENT;
sub EXECUTE_LOAD_QUERY_EVENT;
sub XID_EVENT;
sub STOP_EVENT;
sub DELETE_FILE_EVENT;
sub LOAD_EVENT;
sub HEARTBEAT_LOG_EVENT;
sub BEGIN_LOAD_QUERY_EVENT;
sub PRE_GA_WRITE_ROWS_EVENT;
sub QUERY_EVENT;
sub USER_VAR_EVENT;
sub GTID_LOG_EVENT;
sub IGNORABLE_LOG_EVENT;
sub UPDATE_ROWS_EVENT_V1;
sub CREATE_FILE_EVENT;
sub DELETE_ROWS_EVENT;
sub USER_DEFINED;
sub RAND_EVENT;
sub START_EVENT_V3;
sub WRITE_ROWS_EVENT;
sub ANONYMOUS_GTID_LOG_EVENT;
sub UPDATE_ROWS_EVENT;
sub UNKNOWN_EVENT;
sub APPEND_BLOCK_EVENT;
sub STRING_TYPE;
sub REAL_TYPE;
sub INT_TYPE;
sub ROW_TYPE;
sub DECIMAL_TYPE;
sub VALUE_TYPE_COUNT;
sub STMT_END_F;
sub NO_FOREIGN_KEY_CHECKS_F;
sub RELAXED_UNIQUE_CHECKS_F;
sub COMPLETE_ROWS_F;
sub INVALID_INT_EVENT;
sub LAST_INSERT_ID_EVENT;
sub INSERT_ID_EVENT;
sub ERR_OK;
sub ERR_EOF;
sub ERR_FAIL;
sub ERR_CHECKSUM_ENABLED;
sub ERR_CHECKSUM_QUERY_FAIL;
sub ERR_CONNECT;
sub ERR_BINLOG_VERSION;
sub ERR_PACKET_LENGTH;
sub ERR_MYSQL_QUERY_FAIL;
sub ERROR_CODE_COUNT;

SCOPE:{
  my @event_classes = ('MySQL::Binlog::Event::AnonymousGtidLog', 'MySQL::Binlog::Event::AppendBlock', 'MySQL::Binlog::Event::BeginLoadQuery', 'MySQL::Binlog::Event::CreateFile', 'MySQL::Binlog::Event::DeleteFile', 'MySQL::Binlog::Event::DeleteRows', 'MySQL::Binlog::Event::DeleteRowsV1', 'MySQL::Binlog::Event::EnumEnd', 'MySQL::Binlog::Event::ExecLoad', 'MySQL::Binlog::Event::ExecuteLoadQuery', 'MySQL::Binlog::Event::Format', 'MySQL::Binlog::Event::GtidLog', 'MySQL::Binlog::Event::HeartbeatLog', 'MySQL::Binlog::Event::IgnorableLog', 'MySQL::Binlog::Event::Incident', 'MySQL::Binlog::Event::IntVar', 'MySQL::Binlog::Event::Load', 'MySQL::Binlog::Event::NewLoad', 'MySQL::Binlog::Event::PreGaDeleteRows', 'MySQL::Binlog::Event::PreGaUpdateRows', 'MySQL::Binlog::Event::PreGaWriteRows', 'MySQL::Binlog::Event::PreviousGtidsLog', 'MySQL::Binlog::Event::Query', 'MySQL::Binlog::Event::Rand', 'MySQL::Binlog::Event::Rotate', 'MySQL::Binlog::Event::RowsQueryLog', 'MySQL::Binlog::Event::Slave', 'MySQL::Binlog::Event::StartV3', 'MySQL::Binlog::Event::Stop', 'MySQL::Binlog::Event::TableMap', 'MySQL::Binlog::Event::Unknown', 'MySQL::Binlog::Event::UpdateRows', 'MySQL::Binlog::Event::UpdateRowsV1', 'MySQL::Binlog::Event::UserDefined', 'MySQL::Binlog::Event::UserVar', 'MySQL::Binlog::Event::WriteRows', 'MySQL::Binlog::Event::WriteRowsV1', 'MySQL::Binlog::Event::Xid');

  sub setup_event_inheritance {
    no strict 'refs';
    foreach my $class (@event_classes) {
      if (not $class->isa("MySQL::Binlog::Event")) {
        push @{$class . "::ISA"}, "MySQL::Binlog::Event";
      }
    }
  }
} # end SCOPE

package
  MySQL::Binlog::Constants;
1;
